name: LocatorToggle
version: '1.3'
author: Axyss
main: dev.axyss.locatorToggle.Main
api-version: '1.21'
softdepend: ["PlaceholderAPI"]

permissions:
  locator.toggle:
    default: true
  locator.radius:
    default: true
  locator.reload:
    default: op
