name: LocatorToggle
version: '1.2'
author: Axyss
main: dev.axyss.locatorToggle.Main
api-version: '1.21'

commands:
  locator:
    description: Toggles locator bar functionality
  radius:
    description: Sets the radius for the locator bar

permission:
  locator.toggle:
    default: true
